### ISSUE TITLE
Some GitHub Tasks

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/make-sass-lint-config#1]
@Snugug I should've prepped the repo some more before transferring it over. Can you please:
- [x] Update the website for this repo to use sasstools.github.io
- [x] Set "master" as the default branch

I'm going to wipe the gh-pages branch and make it an orphan branch instead.

**Comment by benthemonkey** [comment]
I've gone ahead and orphaned gh-pages.

**Comment by Snugug** [comment]
Done and done.
