### ISSUE TITLE
Online Converter Doesn't Work

### ISSUE THREAD

**Issue by stowball** [sasstools/make-sass-lint-config#3]
When trying to use the online converter, I always get the following JS error `convert.js:799 - Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by tdhulster** [comment]
Same error here : 
![sass-lint-error](https://cloud.githubusercontent.com/assets/3808183/10939592/f98bf7fc-8302-11e5-9bad-50031a380443.PNG)

Can be reproduced with this scss-lint configuration :
http://pastebin.com/ckCgiFPn#

**Comment by benthemonkey** [comment]
Should be fixed by 3848302686f07605810d6dd32e0aab6f93820e8e

@stowball can you let me know if it works for you? @tdhulster the tool now works with your provided config file.

Thanks for the feedback!

**Comment by stowball** [comment]
Yep, fixed! Thanks

**Comment by tdhulster** [comment]
Thanks for the fix! Works as expected
